### PR TITLE
Keywords

### PR DESCRIPTION
**Pull request by jagreene**

### CODE REVIEW

**Comment by sihrc** [comment]
Some merge artifacts in the docs:
```
Undocumented arguments in documentation object 'keywords'
...

Bad \usage lines found in documentation object 'make_request':
<<<<<<< HEAD
=======
>>>>>>> 0a45eb1... roxygenized to add keywords files
```

**Comment by anneCarlson** [comment]
These tests aren't passing. Something to do with the man files?

**Comment by jagreene** [comment]
potentially? I'm looking into it now, weirdly all my tests pass locally

**Comment by anneCarlson** [comment]
Merge!

**Pull request merged**
