### PR TITLE
hq-sentiment update

### PR DESCRIPTION
**Pull request by anneCarlson**
I can go through and add an error message for non cloud call of sentimenthq through for all of these later if that is what we decide we need.

### CODE REVIEW

**Comment by anneCarlson** [comment]
Wow, this is old. CR @jagreene @sihrc

**Comment by sihrc** [comment]
It's currently not mergeable :(

**Comment by sihrc** [comment]
Looks fine to me besides that point though. I think I had a look at it before. Fixed some docs for the tests to pass

**Comment by sihrc** [comment]
I'll merge it real quick

**Pull request merged**
